"""Refactor WeeklySummary to new structure

Revision ID: 6910e07d0543
Revises: 
Create Date: 2025-07-16 10:10:43.443875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6910e07d0543'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('productivity_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('burnout_flag', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('excuse_count', sa.Integer(), nullable=True))
        batch_op.drop_column('avg_hours')
        batch_op.drop_column('least_productive_day')
        batch_op.drop_column('most_productive_hours')
        batch_op.drop_column('most_productive_day')
        batch_op.drop_column('least_productive_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('least_productive_hours', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('most_productive_day', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('most_productive_hours', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('least_productive_day', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('avg_hours', sa.FLOAT(), nullable=False))
        batch_op.drop_column('excuse_count')
        batch_op.drop_column('burnout_flag')
        batch_op.drop_column('productivity_score')

    # ### end Alembic commands ###
